version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: npm start
    network_mode: "host"
    environment:
      - TZ=America/Guayaquil
